---
- name: Deploy to Kubernetes (Locally using minikube)
  hosts: localhost
  gather_facts: true  # Enable fact gathering to ensure system compatibility
  tasks:

    # Task 1: Check the system's OS and decide on the package manager
    - name: Gather system facts
      ansible.builtin.setup:

    # Task 2: Ensure Python is installed (Ansible requires Python)
    - name: Check if Python is installed
      command: which python3
      register: python_installed
      failed_when: python_installed.rc != 0
      changed_when: false
      ignore_errors: yes

    - name: Debug if Python is missing
      debug:
        msg: "Python3 is missing. Please manually install Python3."

      when: python_installed.rc != 0

    # Task 3: Ensure pip3 is installed
    - name: Check if pip3 is installed
      command: which pip3
      register: pip_installed
      failed_when: pip_installed.rc != 0
      changed_when: false
      ignore_errors: yes

    - name: Debug if pip3 is missing
      debug:
        msg: "pip3 is missing. Please manually install pip3."

      when: pip_installed.rc != 0

    # Task 4: Ensure Ansible is installed
    - name: Check if Ansible is installed
      command: which ansible
      register: ansible_installed
      failed_when: ansible_installed.rc != 0
      changed_when: false
      ignore_errors: yes

    - name: Debug if Ansible is missing
      debug:
        msg: "Ansible is missing. Please manually install Ansible."

      when: ansible_installed.rc != 0

    # Task 5: Ensure Kubernetes Python client is installed
    - name: Check if Kubernetes Python client is installed
      command: python3 -c "import kubernetes"
      register: kubernetes_client_installed
      failed_when: kubernetes_client_installed.rc != 0
      changed_when: false
      ignore_errors: yes

    - name: Debug if Kubernetes Python client is missing
      debug:
        msg: "Kubernetes Python client is missing. Please manually install the Kubernetes Python client."

      when: kubernetes_client_installed.rc != 0

    # Task 6: Ensure kubectl is installed
    - name: Check if kubectl is installed
      command: which kubectl
      register: kubectl_installed
      failed_when: kubectl_installed.rc != 0
      changed_when: false
      ignore_errors: yes

    - name: Debug if kubectl is missing
      debug:
        msg: "kubectl is missing. Please manually install kubectl."

      when: kubectl_installed.rc != 0

    # Task 7: Ensure minikube is installed
    - name: Check if minikube is installed
      command: which minikube
      register: minikube_installed
      failed_when: minikube_installed.rc != 0
      changed_when: false
      ignore_errors: yes

    - name: Debug if minikube is missing
      debug:
        msg: "minikube is missing. Please manually install minikube."

      when: minikube_installed.rc != 0

    # Task 8: Set kubectl and minikube installation packages dynamically based on the OS
    - name: Set package manager variables based on OS
      set_fact:
        kubectl_package: "{{ 'kubectl' if ansible_facts['os_family'] == 'Debian' else 'kubectl-tools' }}"
        minikube_package: "{{ 'minikube' if ansible_facts['os_family'] == 'Debian' else 'minikube-cli' }}"

    # Task 9: Get the current version of the running deployment (If exists)
    - name: Fetch current deployed image tag
      command: kubectl get deployment nginx-deployment -o=jsonpath='{.spec.template.spec.containers[0].image}'
      register: current_image_tag
      failed_when: current_image_tag.rc != 0
      changed_when: false
      ignore_errors: yes

    - name: Debug current deployed image tag
      debug:
        msg: "Current deployed image tag: {{ current_image_tag.stdout }}"

    # Task 10: Get the latest tag (Version) from the GitHub repository
    - name: Fetch latest version tag
      command: git describe --tags --abbrev=0
      register: latest_version
      changed_when: false  # No need to mark as changed

    - name: Debug the raw output of the git describe command
      debug:
        var: latest_version.stdout

    - name: Set IMAGE_TAG from latest version
      set_fact:
        image_tag: "{{ latest_version.stdout }}"

    - name: Debug image tag being used
      debug:
        msg: "Deploying with image tag: {{ image_tag }}"

    # Task 11: Apply the Kubernetes Nginx deployment with the new image tag
    - name: Apply Nginx Deployment
      kubernetes.core.k8s:
        state: present
        kubeconfig: "~/.kube/config"  # Ensure it's the correct kubeconfig path
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: "ghcr.io/peewpew/devops3/devops3:{{ image_tag }}"
                    imagePullPolicy: Always  # Forces Kubernetes to always pull the latest version
                    ports:
                      - containerPort: 80

    # Task 12: Apply the Kubernetes Nginx Service
    - name: Apply Nginx Service
      kubernetes.core.k8s:
        state: present
        kubeconfig: "~/.kube/config"  # Ensure it's the correct kubeconfig path
        definition: "{{ lookup('file', 'nginx-service.yml') }}"  # Ensure service definition is correct

    # Task 13: Verify the deployment
    - name: Get Kubernetes pods status
      command: kubectl get pods
      register: pod_status

    - name: Display pod status
      debug:
        var: pod_status.stdout

  handlers:
    - name: Rollback to previous version
      kubernetes.core.k8s:
        state: present
        kubeconfig: "~/.kube/config"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: "ghcr.io/peewpew/devops3/devops3:{{ current_image_tag.stdout }}"  # Rollback to previous image
                    imagePullPolicy: Always
                    ports:
                      - containerPort: 80
