name: Docker Image Build and Push

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Lint Dockerfile
      - name: Lint Dockerfile
        run: |
          curl -sL https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint
          hadolint Dockerfile

      # Set environment variables (REPO_NAME, IMAGE_NAME, IMAGE_TAG)
      - name: Set Environment Variables
        run: |
          echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_NAME=devops3" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # Build Docker image with dynamic naming
      - name: Build Docker Image
        run: |
          docker build --no-cache -t ghcr.io/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG .
          docker images  # Verify the image

      # Push Docker image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/$REPO_NAME/$IMAGE_NAME:$IMAGE_TAG
