name: Docker Image Build and Push

on:
  push:
    tags:
      - 'v*.*.*'  # Only run the workflow for version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Lint Dockerfile
      - name: Lint Dockerfile
        run: |
          curl -sL https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint
          hadolint Dockerfile

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image and verify build
      - name: Build Docker Image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/my-image:${{ github.ref_name }} .
          docker images

      # Push Docker image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-image:${{ github.ref_name }}
